### ISSUE TITLE
Add analogue style

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Clock-Abandoned#3]

**Comment by git001** [comment]
It would be nice to have ha 24 Hour analog clock ;-)

![25H clock](https://sc02.alicdn.com/kf/HTB1g_QLKFXXXXaVXVXXq6xXFXXXU/wall-clock-2016-new-plastic-wall-clocks.jpg)

**Comment by Aga-C** [comment]
I like an analog clock (in World Clock tab) in Clock app from OnePlus. It would be great to have a possibility to add something like this (as an option) to the first tab.

![image](https://user-images.githubusercontent.com/85929121/140696239-51cbc676-d885-420f-bc6c-8bcef665f156.png)

**Comment by KrasnayaPloshchad** [comment]
This feature is already available in [Clock L](https://apkpure.com/clock-l/com.moblynx.clockl).
